### ISSUE TITLE
search()->get() returns a maximum of 20 items

### ISSUE THREAD

**Issue by scottgrayson** [shokme/laravel-scout-meilisearch#104]
1. seed many rows to User table
2. import User to scout meilsearch index
3. search for 'a' in meilisearch web UI and note the number of documents
4. search for 'a' in tinker using User::search('a')->get()->count()

Expected:
meilisearch web UI and laravel scout search should return the same number of documents

Problem:
meilisearch returns 23428 results
scout returns 20 results

**Comment by curquiza** [comment]
Hello @scottgrayson!

The search engine (MeiliSearch) returns 20 results by default, that's why the plugin only returns 20 results.
You might want to increase this limit by setting a new value to the search parameter `limit`.
Our README describes how to do a custom search with search parameters -> https://github.com/meilisearch/meilisearch-laravel-scout#custom-search-

More about search parameters: https://docs.meilisearch.com/reference/features/search_parameters.html#search-parameters
More about the search parameter `limit`: https://docs.meilisearch.com/reference/features/search_parameters.html#limit
