### ISSUE TITLE
Include facetsDistribution in paginate() response?

### ISSUE THREAD

**Issue by foreverheavy** [shokme/laravel-scout-meilisearch#118]
Loving Meilisearch so far, guys... Only think holding me back from integrating it into our app is a lack of clarity on how to access the extra metadata like facetsDistribution.

I can currently access facetsDistribution by using raw() when executing the query, so my temporary workaround is calling the raw search function, then the traditional paginate query right afterwards. Is there a way to integrate the facetsDistribution response into the paginate response so I don't have to do this hacky, resource-intensive workaround?

Thanks!

**Comment by curquiza** [comment]
Hello @foreverheavy!

Thanks for trying MeiliSearch 😄 
If I'm correct, we don't provide any possibility like this one for the moment since we want to be totally compliant with the official Laravel/Scout package. See this issue for more details #111.

However, to avoid calling twice the server, you can perform your pagination in a custom search, at the same time as the `facetsDistribution` parameter:
```php
User::search('your query', function (Indexes $meilisearch, $query, $options) {
        $options['offset'] = 10;
        $options['limit'] = 5;
        $options['facetsDistribution'] = ['your facet'];

        return $meilisearch->search($query, $options);
})->raw();
```
Here is the README section about custom search: 
https://github.com/meilisearch/meilisearch-laravel-scout#custom-search-

`offset` and `limit` are what the `paginate()` method uses.
The `paginate()` method also uses the `getTotalCount()` method to know the total number of hits, which uses the `nbHits` returned in the `raw` search. See https://github.com/meilisearch/meilisearch-laravel-scout/blob/e180d66163c79248f48bb15d0ea3081b073c9593/src/Engines/MeilisearchEngine.php#L201-L204

You have all the elements to implement the pagination, even if it's less convenient than the `paginate()` method, it removes the double HTTP call.

I hope I understood your issue and it will help you. Feel free to ask any question about my explanation 🙂
