### ISSUE TITLE
How to deploy and use laravel-scout and Meilisearch to ec2 instance

### ISSUE THREAD

**Issue by madhavanswami** [shokme/laravel-scout-meilisearch#123]
I am new to laravel and meilisearch. I know how to deploy meilisearch alone on ec2 but now i want to use laravel with meilisearch. 
i am not able to understand how to get the usecase running. Someone please help me.
Thanks

**Comment by madhavanswami** [comment]
> Hello @madhavanswami!
> Welcome to MeiliSearch! slightly_smiling_face
> You should follow the steps in the README -> https://github.com/meilisearch/meilisearch-laravel-scout
> I'm moving this issue to meilisearch-laravel-scout

how can i make a connection with laravel which is deployed on ec2 instance with api ?

**Comment by madhavanswami** [comment]
For a beginner the reference documents seems very intimidating. There are not proper examples to understand. Till the installation and setup part the docs are usable but for the implementation I think there should be more documentation

**Comment by curquiza** [comment]
What is intimidating? This would help me to guide you 🙂
If you are a beginner with laravel, you should take a look at the [laravel documentation](https://laravel.com/docs/8.x) first because the integration of MeilISearch for laravel in completely integrated into the laravel environment and this would help you understand our README.

**Comment by hi019** [comment]
Also check out the Laravel Scout docs: https://laravel.com/docs/8.x/scout
