### ISSUE TITLE
Engine uses the eloquent getScoutKey() to get key values but uses getKeyName() to get the name of the key

### ISSUE THREAD

**Issue by keithza** [shokme/laravel-scout-meilisearch#126]
Scout allows you to customize the Eloquent value **and** key name used for the keys in your index. 

The Meilisearch engine uses the getScoutKey() method to get the key value however, makes use of the getKeyName() method instead of the getScoutKeyName() method for the value.

I would like to change this behaviour to use the getScoutKeyName() method instead of getKeyName(). May I go ahead with a PR?

**Comment by mmachatschek** [comment]
I think that this would not work out as expected.

The `getScoutKeyName()` method is only used for fetching the models from the database not from the search index. It looks to me as if the documentation and the method description on laravel/scout is not correct.

This means that if we change `getKeyName()` to `getScoutKeyName()` in the MeiliSearchEngine class, everyone that uses the library also would need to add a `toSearchableArray` method on each model and set the primaryKey name of that model to `getScoutKeyName()` and the value to `getScoutKey()`.

For Aloglia this works because there is a mandatory field `ObjectID` that is sent with each create/update/delete. Whereas the identifier for a MeiliSearch index basically can be set to anything you want.

@keithza maybe you can point this out in the issues at laravel/scout

**Comment by keithza** [comment]
@mmachatschek there definitely seems to be an issue with laravel/scout and the documentation as well as the behavior of `getScoutKeyName()` in the laravel/scout code as well. The base method returns the qualified name meaning `<table>.<key>`. This causes issues. 

I still feel that this should apply so that using the --key option in the scout:index command can be implemented without the need for implementing the change to the `toSearchableArray()` method and allow use of the custom key name for tables without an `id` field. 

If `getScoutKeyName()` was implemented correctly in laravel/scout only one change would need to be made in the `getKeyName()` method and that change would cascade.

Regardless, before this can happen, laravel/scout needs to be amended.
