### ISSUE TITLE
Ranking rules and synonim

### ISSUE THREAD

**Issue by rodrigore** [shokme/laravel-scout-meilisearch#16]
Hi! I'm just starting with meilisearch and I was wondering if is possible to change the ranking rules of an index with this package or if I need to make the petition myself to the meilisearch endpoint.

if my dataset is in another language, for example spanish, meilisearch I read that for stopword use some kind of tokenization of latin word, but not sure if the synonim work for Spanish?

I hope that someone can clarify and thank you for this amazing tool.

**Comment by curquiza** [comment]
Hello @rodrigore! Thanks for using MeiliSearch 😁

> I was wondering if is possible to change the ranking rules of an index with this package or if I need to make the petition myself to the meilisearch endpoint.

You cannot change the settings of MeiliSearch (so, the ranking rules) with this package. But you can do it:
- with the [SDK PHP for MeiliSearch](https://github.com/meilisearch/meilisearch-php) used by this Laraval-Scout package. See [these lines of codes](https://github.com/meilisearch/meilisearch-php/blob/f073e2b658a7089ed00bf8b1dcf6da532fa1306d/src/Index.php#L142). Sorry it's not documented yet.
- using the MeiliSearch endpoint directly, as you suggested it! For a better experience, we provide a [Postman collection](https://docs.meilisearch.com/resources/postman_collection.html).

> if my dataset is in another language, for example spanish, meilisearch I read that for stopword use some kind of tokenization of latin word, but not sure if the synonim work for Spanish?

Not sure to understand what you mean. Can you give me an example? 🙂

Don't hesitate to [join us to our Slack](https://slack.meilisearch.com/), so that we can discuss easily, especially if you choose to use the undocumented part 🙂

**Comment by rodrigore** [comment]
Thank you for the answer, you help me a lot.

I sent a pull request #17 about the steps or methods to update the settings.

About the question that you dont understand, I mean instead of 'Stopwords' It should be 'Typos'. 
So the question is that the typos works only for english words or still work for spanish?

Thank you!

**Comment by curquiza** [comment]
> I sent a pull request #17 about the steps or methods to update the settings.

Thanks! I've just answered to your PR 🙂

> About the question that you dont understand, I mean instead of 'Stopwords' It should be 'Typos'.
So the question is that the typos works only for english words or still work for spanish?

The `typo` randking rules is not related to a language, so it will work for spanish words too 🙂
To explain it quickly, if you type `abcdfeg`, MeiliSearch will look for documents containing `abcdfeg` but also documents containing:
- almost the same word by reversing some letters, for example `abcdefg`
- almost the same word by adding some missing letters, for example `abcdefgh`

You can read more about [typo-tolerance here](https://docs.meilisearch.com/guides/advanced_guides/typotolerance.html) 🙂

**Comment by rodrigore** [comment]
Nice! thank you for clarifying me.
