### ISSUE TITLE
Double forward slashes - route generation.

### ISSUE THREAD

**Issue by Cmarenburg** [shokme/laravel-scout-meilisearch#19]
Just curious if anyone is experiencing routes being generate with a double forward slash on requests (ending up within incoming requests to the Meilisearch server like `POST //indexes//documents?primaryKey=id` (taken from the console), it's resulting in 404's not found with the server, when built with the binary.  
I'm not really sure where to go from here. When I generate a HTTP request via a rest client it all works fine. Anyone else have any issues?
Current version used is 0.10.0

**Comment by curquiza** [comment]
Hello @Cmarenburg!
Is it an issue that you noticed on MeiliSearch (with `curl` for example) or with this laravel package only? 

### Edit
I've just tested it, it's a behavior of MeiliSearch.
Could you open an issue on the [MeiliSearch repository](https://github.com/meilisearch/MeiliSearch/issues/new) instead? 🙂

I close this issue since it's not linked to the Laravel SDKs 😉
