### ISSUE TITLE
Meilisearch can't import products (Request Entity Too Large)

### ISSUE THREAD

**Issue by KariUs123** [shokme/laravel-scout-meilisearch#79]
I have been trying to import products to the meilisearch and I get this error `MeiliSearch\Exceptions\HTTPRequestException  : Request Entity Too Large` is this because of the latest version of meilisearch and how do I fix this?

`private function parseResponse(ResponseInterface $response)`
      `179|     {`
         `180|         if ($response->getStatusCode() >= 300) {`
        `181|             $body = json_decode($response->getBody()->getContents(), true) ?? $response->getReasonPhrase();`
        `> 182|             throw new HTTPRequestException($response->getStatusCode(), $body);`
    `183|         }`

**Comment by curquiza** [comment]
Hello, this is not due to MeiliSearch but probably your Nginx -> https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/
Also, when you will set up your Nginx to support larger payloads, don't forget to set up also MeiliSearch -> https://docs.meilisearch.com/guides/advanced_guides/configuration.html#options.
Indeed, the payload size limit of MeiliSearch (with the v0.18.0) is 100MB -> https://docs.meilisearch.com/guides/advanced_guides/known_limitations.html#other-limitations
